In [4]:
import numpy as np

In [32]:
a=np.array([1,2,3,4,5,6])

In [33]:
a

array([1, 2, 3, 4, 5, 6])

In [34]:
a.shape

(6,)

In [37]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [9]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [10]:
np.random.randint(0,10,size=(5,5))

array([[0, 7, 7, 1, 5],
       [0, 8, 1, 8, 6],
       [5, 2, 8, 1, 3],
       [7, 7, 6, 4, 5],
       [3, 5, 9, 7, 6]])

In [13]:
a=np.ones((3,3))
b=np.zeros((3,3))

In [14]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a+b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.concatenate([a,b], axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [19]:
np.concatenate([a,b], axis=-1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [20]:
np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.hstack([a,b])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [22]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
d.ndim

3

In [24]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
d.shape

(2, 2, 2)

In [26]:
d.size

8

In [6]:
arr1=np.array([1,2,3,4,5])

In [7]:
arr1[:,np.newaxis,np.newaxis].shape

(5, 1, 1)

In [8]:
np.sum(arr1)

15

In [9]:
np.max(arr1)

5

In [10]:
randNum=np.random.randint(1,100,size=(6,6))

In [11]:
randNum

array([[58, 68, 92, 91, 26, 26],
       [23, 90, 39, 10, 95, 89],
       [24, 58, 20, 52, 97, 79],
       [61, 74, 89, 23, 49, 78],
       [ 7, 65, 97, 52, 79, 48],
       [ 2, 40, 34, 56, 83, 97]])

In [13]:
np.sum(randNum,axis=1)

array([361, 346, 330, 374, 348, 312])

In [14]:
np.sum(randNum)

2071