In [31]:
import numpy as np

In [32]:
a=np.array([1,2,3,4,5,6])

In [33]:
a

array([1, 2, 3, 4, 5, 6])

In [34]:
a.shape

(6,)

In [37]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(2,4,8)

array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
       3.42857143, 3.71428571, 4.        ])

In [9]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [10]:
np.random.randint(0,10,size=(5,5))

array([[0, 7, 7, 1, 5],
       [0, 8, 1, 8, 6],
       [5, 2, 8, 1, 3],
       [7, 7, 6, 4, 5],
       [3, 5, 9, 7, 6]])

In [13]:
a=np.ones((3,3))
b=np.zeros((3,3))

In [14]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a+b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.concatenate([a,b], axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [19]:
np.concatenate([a,b], axis=-1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [20]:
np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.hstack([a,b])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [22]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
d.ndim

3

In [24]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
d.shape

(2, 2, 2)

In [26]:
d.size

8